### ISSUE TITLE
Improve performance of dwm_status

### ISSUE THREAD

**Issue by pickfire** [kaihendry/dwm#1]
Hi, In My Humble Opinion, I don't think that you need to update the temperature every second. This will do the trick:
```bash
#!/bin/bash

separator="│"
i=0

while (i+=1; sleep 1); do
  if [ $(($i%5)) == 0 ]; then
    uptimes=$(uptime | cut -d, -f3-3 | cut -d: -f2 | xargs printf)
  fi
  dates=$(date '+%a %d %b %T')

  xsetroot -name "$uptimes $separator $dates"
done
```
That's is how I do it, focus at the **5**. If you really need performance, rewritting it in c will do.

Good luck and have a nice day!

**Comment by kaihendry** [comment]
You are referring to https://github.com/kaihendry/dotfiles/blob/master/bin/dwm_status#L106 right?

I like it every second so I can see network changes quickly. But yeah, it would be way more efficient if it was longer cycle.

Were you feeling sorry for me after seeing https://www.youtube.com/watch?v=tIEpTh2LhB0 ? ;)

**Comment by pickfire** [comment]
Yeah, I saw that too.

I mean you can refresh some command every second and other a few second.

**Comment by kaihendry** [comment]
Oh, now I get what you are saying. Hmmm ! But is it really worth the effort? Do you use my dwm_status?

**Comment by pickfire** [comment]
No, I created my own which is:
```bash
#!/bin/bash

separator="│"
i=0

while (i+=1; sleep 1); do
  [[ $(($i%5)) == 0 ]] && uptimes=$(uptime | cut -d, -f3-4 | cut -d: -f2 | xargs printf)
  dates=$(date '+%a %d %b %T')

  xsetroot -name "$uptimes $separator $dates"
done
```
It is an update for the one above. I think I will add network after I add colors to the status. Look at the status2d patch, I still can't get it work.
